SELECT 
  gid::integer, -- NOT NULL
  the_geom::geometry(Point,2056), 
  location_x::real, 
  location_y::real, 
  elevation_z::real, 
  anz::integer, 
  length::real, 
  date::date, 
  restriction::boolean, 
  restricted_until::date, 
  id_bohrbewilligung::integer, -- NOT NULL
  verfasser::character varying, 
  bemerkungen::text, 
  weitere_informationsquellen::character varying, 
  last_modified_g1::timestamp without time zone, 
  contact_kind::character varying, 
  name::character varying, 
  adress::character varying, 
  email::character varying, 
  tel::character varying, 
  website::character varying, 
  last_modified_g2::timestamp without time zone, 
  depth_bedrock::real, 
  groundwater::boolean, 
  ok_terrain::real, 
  ok_rohr::real, 
  bezeichnung::character varying, 
  gwsp_min::real, 
  gwsp_max::real, 
  date_gwsp_min::date, 
  date_gwsp_max::date, 
  gwsp_mittel::real, 
  uk_rohr::real, 
  uk_deckschicht::real, 
  pumpversuch::real, 
  last_modified_g3::timestamp without time zone, 
  id::integer, -- NOT NULL
  id_ent_h2o_andere::character varying, 
  id_neu_seit_2005::character varying, 
  id_ent_h2o_still::character varying, 
  nr_bohrkat::character varying, 
  id_erdsonden::character varying, 
  id_gww::character varying, 
  tiefe::real, 
  kind::dbu_aue_gsbohrung.dbu_aue_gsbohrung_borehole_kind, 
  orientation::dbu_aue_gsbohrung.dbu_aue_gsbohrung_borehole_orientation, 
  id_ent_h2o_gew_ind::character varying, 
  id_bohrkataster_alt::integer, 
  tmp_man_aufteilung::boolean, 
  verifikation_geometrie::dbu_aue_gsbohrung.dbu_aue_gsbohrung_borehole_verifikation, 
  kwert::double precision, 
  ok_stauer::double precision, 
  messnetz::character varying, 
  messung_moeglich::boolean, 
  ablagenummer::integer, 
  bohrprofil::dbu_aue_gsbohrung.dbu_aue_gsbohrung_borehole_bohrprofil, 
  parz::character varying, 
  grundbuch::character varying, 
  publikation::boolean, -- NOT NULL
  bohrprofil_pdf::character varying,

  -- additional derived attributes
  v.kategorie,
  string_to_array(bohrprofil_pdf, '\') as arr_pdf

FROM {{ source('dbu_aue_gsbohrung', 'borehole') }} as b
LEFT JOIN {{ ref('stg_view_borehole_kategorie') }} as v
  ON v.id_borehole = b.id