sources:
  - name: prod_gl_biotope
    database: "{{ target.database }}"
    schema: prod_gl_biotope
    tables:
      - name: biotope_to_sf
      - name: cat_kartierungsgrundlage
      - name: cat_herkunft
      - name: cat_biotopart


  - name: ch_kt_auengebiete
    database: "{{ target.database }}"
    schema: ch_kt_auengebiete
    tables:
      - name: kartierungsgrundlage_catalogue
      - name: bedeutung_catalogue

