sources:
  - name: prod_gl_biotope
    database: "{{ target.database }}"
    schema: prod_gl_biotope
    tables:
      - name: biotope_to_sf
      - name: biotope_to_li
      - name: biotope_to_pt
      - name: cat_kartierungsgrundlage
      - name: cat_herkunft
      - name: cat_biotopart


  - name: ch_kt_auengebiete
    database: "{{ target.database }}"
    schema: ch_kt_auengebiete
    tables:
      - name: kartierungsgrundlage_catalogue
      - name: bedeutung_catalogue

  - name: ch_kt_hochmoore
    database: "{{ target.database }}"
    schema: ch_kt_hochmoore
    tables:
      - name: hm_kartierungsgrundlage_catalogue
      - name: hm_bedeutung_catalogue

  - name: ch_kt_flachmoore
    database: "{{ target.database }}"
    schema: ch_kt_flachmoore
    tables:
      - name: kartierungsgrundlage_catalogue
      - name: bedeutung_catalogue

  - name: ch_kt_trockenwiesen
    database: "{{ target.database }}"
    schema: ch_kt_trockenwiesen
    tables:
      - name: kartierungsgrundlage_catalogue
      - name: bedeutung_catalogue

  - name: ch_kt_biotope_punkte
    database: "{{ target.database }}"
    schema: ch_kt_biotope_punkte
    tables:
      - name: bio_kartierungsgrundlage_catalogue
      - name: bio_bedeutung_catalogue
      - name: bio_typ_catalogue
