services:
  dbt-dev: 
    image: dbt_image:dev
    container_name: dbt-container
    network_mode: host  
    volumes:
      - ../src/dbt:/src/dbt          
    # environment:
    #  - DISPLAY=host.docker.internal:0.0 # set display environment to local host IP
    stdin_open: true
    tty: true

  postgis-srv:
    image: postgis:dev
    container_name: postgis-container
    network_mode: host
