## This is the Dockerfile for the dbt image

# Base image
FROM python:3.11-slim

# Install dbt and dbt-postgres extension through pip
RUN pip install dbt-core dbt-postgres

# Install other dependencies
RUN apt-get update && apt-get install -y \
    git \
    lsof

# Set working directory (default location opened after starting container)
WORKDIR /home/dbt
