name: 'dbt_gslw'
version: '1.0.0'

profile: 'dbt_gslw_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  

on-run-start:
  - ALTER SEQUENCE dbt_gslw.t_ili2db_seq RESTART WITH {{ var('starting_data_tid') }}

models:
  dbt_gslw:
    +grants:
      select: ['dbu_aue_gslw_read']
    +post-hook: 
    - 'ALTER {{model.config.materialized}} {{this}} OWNER TO "dbu_aue_gslw_write"'
