select
  {{ adapter.quote("schluessel") }},
  ST_SetSRID({{ adapter.quote("geom") }}, 2056) as geometrie,
  {{ adapter.quote("objektname") }} as aname,
  {{ adapter.quote("lokalbezeichnung") }},
  {{ adapter.quote("gemeinde") }},
  {{ adapter.quote("postleitzahl") }},
  {{ adapter.quote("x-koordinate") }} as x_koordinate,
  {{ adapter.quote("y-koordinate") }} as y_koordinate,
  {{ adapter.quote("parz nr") }} as part_nr,
  {{ adapter.quote("fassungseigentuemer") }},
  {{ adapter.quote("ok terrain") }} as ok_terrain,
  {{ adapter.quote("schachtueberstand") }},
  {{ adapter.quote("ordnungs-nr") }} as ordnungs_nr,
  {{ adapter.quote("lagegenauigkeit") }},
  {{ adapter.quote("verwendungszweck") }},
  {{ adapter.quote("verwendungsart") }},
  {{ adapter.quote("fassungsart") }},
  {{ adapter.quote("fassungszustand") }},
  {{ adapter.quote("fassungsabdeckung") }},
  {{ adapter.quote("schachttyp") }},
  {{ adapter.quote("datenherkunft") }},
  {{ adapter.quote("kontaktperson") }},
  {{ adapter.quote("bemerkungen objektdaten") }} as bemerkungen,
  {{ adapter.quote("foto") }},
  {{ adapter.quote("foto-negativ-nr 1") }} as foto_negativ_nr_1,
  {{ adapter.quote("foto-negativ-nr 2") }} as foto_negativ_nr_2,
  {{ adapter.quote("foto-negativ-nr 3") }} as foto_negativ_nr_3,
  {{ adapter.quote("fassung") }},
  {{ adapter.quote("schutzzone") }},
  {{ adapter.quote("anzahl zuleitungen") }} as anzahl_zuleitungen,
  {{ adapter.quote("schloss") }},
  {{ adapter.quote("aufgenommen durch") }} as aufgenommen_durch,
  {{ adapter.quote("erhebungsdatum") }},
  {{ adapter.quote("alte ordnungs nr") }} as alte_ordnungs_nr,
  {{ adapter.quote("feldbegehung") }},
  {{ adapter.quote("objektbereinigung") }},
  {{ adapter.quote("wva-nutzung") }} as wva_nutzung,
  {{ adapter.quote("wva-nutzung ergaenzen") }} as wva_nutzung_ergaenzen,
  {{ adapter.quote("wva-nutzung streichen") }} as wva_nutzung_streichen,
  {{ adapter.quote("wva-nutzung lage neu") }} as wva_nutzung_lage_neu
from {{ source('raw_sources', 'src_access_objektdaten') }}
