select
  {{ adapter.quote("schluessel") }} as pkey_src,
  {{ adapter.quote("objektname") }} as aname,
  {{ adapter.quote("lokalbezeichnung") }},
  {{ adapter.quote("gemeinde") }} as ortschaft,
  {{ adapter.quote("postleitzahl") }},
  {{ adapter.quote("x-koordinate") }} as x_koordinate,
  {{ adapter.quote("y-koordinate") }} as y_koordinate,
  {{ adapter.quote("parz nr") }} as parz_nr,
  {{ adapter.quote("fassungseigentuemer") }},
  {{ adapter.quote("ok terrain") }} as hoehe,
  {{ adapter.quote("schachtueberstand") }},
  {{ adapter.quote("ordnungs-nr") }}::varchar as ordnungs_nr,
  {{ adapter.quote("lagegenauigkeit") }},
  {{ adapter.quote("verwendungszweck") }},
  {{ adapter.quote("verwendungsart") }},
  {{ adapter.quote("fassungsart") }},
  {{ adapter.quote("fassungszustand") }},
  {{ adapter.quote("fassungsabdeckung") }},
  {{ adapter.quote("schachttyp") }},
  {{ adapter.quote("datenherkunft") }},
  {{ adapter.quote("kontaktperson") }},
  {{ adapter.quote("bemerkungen objektdaten") }} as bemerkungen,
  {{ adapter.quote("foto") }},
  {{ adapter.quote("foto-negativ-nr 1") }} as foto_negativ_nr_1,
  {{ adapter.quote("foto-negativ-nr 2") }} as foto_negativ_nr_2,
  {{ adapter.quote("foto-negativ-nr 3") }} as foto_negativ_nr_3, 
  {{ adapter.quote("fassung") }},
  {{ adapter.quote("schutzzone") }} as schutzzone,
  {{ adapter.quote("anzahl zuleitungen") }} as anzahl_zuleitungen,
  {{ adapter.quote("schloss") }},
  {{ adapter.quote("aufgenommen durch") }} as aufgenommen_durch,
  to_date(NULLIF({{ adapter.quote("erhebungsdatum") }},''), 'DD.MM.YYYY') as erhebungsdatum,
  {{ adapter.quote("alte ordnungs nr") }} as alte_ordnungs_nr,
  to_date(NULLIF({{ adapter.quote("feldbegehung") }},''), 'DD.MM.YYYY') as feldbegehung,
  to_date(NULLIF({{ adapter.quote("objektbereinigung") }},''), 'DD.MM.YYYY') as objektbereinigung,
  {{ adapter.quote("wva-nutzung") }} as wva_nutzung,
  {{ adapter.quote("wva-nutzung ergaenzen") }} as wva_nutzung_ergaenzen,
  {{ adapter.quote("wva-nutzung streichen") }} as wva_nutzung_streichen,
  {{ adapter.quote("wva-nutzung lage neu") }} as wva_nutzung_lage_neu,
  ST_Transform({{ adapter.quote("geom") }}, 2056) as geometrie
from {{ source('raw_sources', 'src_access_objektdaten') }}

