SELECT 
  {{ var('baskets')['basket_quellkataster_alpquellen']['t_id'] }}::bigint as t_basket,
  '{{ var('classnames')['Quelle_intern'] }}'::character varying as t_type,
  'GL_' || Row_Number() OVER (ORDER BY fid)::character varying as identifikator,
  aname::character varying,
  grundwasserleiter_typ::character varying,
  quelltyp::character varying,
  fassungsart::character varying,
  nutzungszustand::character varying,
  trinkwasser::character varying
  zweck::character varying,
  oeffentliches_interesse::character varying,
  schuettung_minimal::numeric,
  schuettung_mittel::numeric,
  schuettung_maximal::numeric,
  NULL as zustroembereich_erforderlich::character varying,
  ST_SetSRID(ST_Point(x_koordinaten, y_koordinaten), 2056) as geometrie,
  hoehe,
  notwasserversorgung,
  NULL as name_wv::character varying,
  NULL as ordnungs_nr::character varying,
  NULL as ortschaft::character varying,
  NULL as postleitzahl::character varying,
  NULL as parznr::character varying,
  NULL as lagegenauigkeit::character varying,
  NULL as schachtueberstand::integer,
  NULL as fassungsart_beschreibung::character varying,
  NULL as fassungsabdeckung::character varying,
  NULL as fassungszustand,::character varying
  NULL as schachttyp::character varying,
  NULL as anzahl_zuleitungen::integer,
  NULL as schloss::boolean,
  NULL as fassungseigentuemer::character varying,
  NULL as verwendungsart::character varying,
  NULL as verwendungszweck_beschreibung::character varying,
  NULL as wva_nutzung::boolean,
  NULL as wva_nutzung_ergaenzen::boolean,
  NULL as wva_nutzung_streichen::boolean,
  NULL as wva_nutzung_lage_neu::boolean,
  NULL as datenherkunft::character varying,
  NULL as aufgenommen_durch::character varying,
  NULL as erhebungsdatum::date,
  NULL as feldbegehung::date,
  NULL as objektbereinigung::date,
  NULL as schutzzone_erforderlich::boolean,
  NULL as kontaktperson::character varying,
  NULL as bemerkungen::character varying
FROM {{ ref("staging_alpquellen") }}



