{% set null_substitute = -1.00 %} -- NOT NULL workaround

SELECT 
  nextval('dbu_aue_quellkataster.t_ili2db_seq'::regclass) as t_id,
  {{ var('baskets')['basket_quellkataster_alpquellen']['t_id'] }}::bigint as t_basket,
  '{{ var('classnames')['Quelle_intern'] }}'::character varying as t_type,
  'GL_' || Row_Number() OVER (ORDER BY fid)::character varying as identifikator,
  aname::character varying,
  grundwasserleiter_typ::character varying,
  quelltyp::character varying,
  fassungsart::character varying,
  nutzungszustand::character varying,
  trinkwasser::character varying,
  zweck::character varying,
  oeffentliches_interesse::character varying,
  COALESCE(schuettung_minimal, {{null_substitute}})::numeric as schuettung_minimal,
  COALESCE(schuettung_mittel, {{null_substitute}})::numeric as schuettung_mittel,
  COALESCE(schuettung_maximal, {{null_substitute}})::numeric as schuettung_maximal,
  NULL::character varying as zustroembereich_erforderlich,
  ST_SetSRID(ST_Point(x_koordinaten, y_koordinaten), 2056) as geometrie,
  hoehe::numeric,
  notwasserversorgung::varchar,
  NULL::character varying as name_wv,
  NULL::character varying as ordnungs_nr,
  NULL::character varying as ortschaft,
  NULL::character varying as postleitzahl,
  NULL::character varying as parznr,
  NULL::character varying as lagegenauigkeit,
  NULL::integer as schachtueberstand,
  NULL::character varying as fassungsart_beschreibung,
  NULL::character varying as fassungsabdeckung,
  NULL::character varying as fassungszustand,
  NULL::character varying as schachttyp,
  NULL::integer as anzahl_zuleitungen,
  NULL::boolean as schloss,
  NULL::character varying as fassungseigentuemer,
  NULL::character varying as verwendungsart,
  NULL::character varying as verwendungszweck_beschreibung,
  NULL::boolean as wva_nutzung,
  NULL::boolean as wva_nutzung_ergaenzen,
  NULL::boolean as wva_nutzung_streichen,
  NULL::boolean as wva_nutzung_lage_neu,
  NULL::character varying as datenherkunft,
  NULL::character varying as aufgenommen_durch,
  NULL::date as erhebungsdatum,
  NULL::date as feldbegehung,
  NULL::date as objektbereinigung,
  NULL::boolean as schutzzone_erforderlich,
  NULL::character varying as kontaktperson,
  NULL::character varying as bemerkungen
FROM {{ ref("staging_alpquellen") }}

