SELECT 
  pt.gid::integer,
  pt.kanton::character varying,
  pt.objekt_nummer::character varying,
  pt.objekt_name::character varying,
  pt.teilobj_nr::character varying,
  pt.teilobj_name::character varying,
  pt.biotopart::character varying,
  pt.beschreibung::character varying,
  pt.herkunft::character varying,
  pt.kartierungsgrundlage::character varying,
  pt.bedeutung::character varying,
  pt.rechtsstatus::character varying,
  pt.publikation::boolean,
  pt.fotos::text,
  pt.spezart::text,
  pt.entscheid::character varying,
  pt.intern_nutzung::character varying,
  pt.intern_gefaehrdung::character varying,
  pt.intern_empfehlung::character varying,
  pt.intern_datum_erhebung::date,
  pt.intern_bearbeiterimfeld::character varying,
  pt.intern_kommentar::text,
  pt.intern_letzte_mutation::date,
  pt.intern_mutationsgrund::character varying,
  pt.intern_spezart::text,
  pt.gem_parz_liste::character varying,
  pt.gem_bezeichnung_lage::character varying,
  pt.gem_beschreibung_objekt::character varying,
  pt.gem_ausfuehrliche_beschreibung_objekt::text,
  pt.gem_bemerkungen_besonderheiten::text,
  pt.gem_biodiversitaet_oekologie::character varying,
  pt.gem_landschaftspraegung::character varying,
  pt.gem_vernetzungsfunktion::character varying,
  pt.gem_gesamtbeurteilung::character varying,
  pt.gem_schutzziele::text,
  pt.gem_empfehlung::text,
  pt.gem_aenderung_vorhandenes_biotop::boolean,
  pt.intern_letzte_aenderung::date,
  pt.last_modified::date,
  pt.last_user::character varying,
  pt.geometrie::geometry(MultiPoint,2056),
  pt.oid_uuid::uuid,
  pt.lebensraumnummer::character varying,
    -- additional utility columns
  a_bio_typ.bio_typ as bafu_bio_typ
FROM {{ source('prod_gl_biotope', 'biotope_to_pt') }} as pt
LEFT JOIN {{ ref('assignment_table_bio_typ') }} as a_bio_typ
  ON a_bio_typ.lebensraumnummer = pt.lebensraumnummer
