SELECT 
  gid::integer,
  kanton::character varying,
  objekt_nummer::character varying,
  objekt_name::character varying,
  teilobj_nr::character varying,
  teilobj_name::character varying,
  biotopart::character varying,
  beschreibung::character varying,
  herkunft::character varying,
  kartierungsgrundlage::character varying,
  bedeutung::character varying,
  rechtsstatus::character varying,
  publikation::boolean,
  fotos::text,
  spezart::text,
  entscheid::character varying,
  intern_nutzung::character varying,
  intern_gefaehrdung::character varying,
  intern_empfehlung::character varying,
  intern_datum_erhebung::date,
  intern_bearbeiterimfeld::character varying,
  intern_kommentar::text,
  intern_letzte_mutation::date,
  intern_mutationsgrund::character varying,
  intern_spezart::text,
  gem_parz_liste::character varying,
  gem_bezeichnung_lage::character varying,
  gem_beschreibung_objekt::character varying,
  gem_ausfuehrliche_beschreibung_objekt::text,
  gem_bemerkungen_besonderheiten::text,
  gem_biodiversitaet_oekologie::character varying,
  gem_landschaftspraegung::character varying,
  gem_vernetzungsfunktion::character varying,
  gem_gesamtbeurteilung::character varying,
  gem_schutzziele::text,
  gem_empfehlung::text,
  gem_aenderung_vorhandenes_biotop::boolean,
  intern_letzte_aenderung::date,
  flaeche_m2::integer,
  last_modified::date,
  last_user::character varying,
  geometrie::geometry(MultiPolygon,2056),
  oid_uuid::uuid,
  id_old::integer,
  lebensraumnummer::character varying,
  -- additional utility columns
  row_number() over() as link_key
FROM {{ source('prod_gl_biotope', 'biotope_to_sf') }}