SELECT 
  li.gid::integer,
  li.kanton::character varying,
  li.objekt_nummer::character varying,
  li.objekt_name::character varying,
  li.teilobj_nr::character varying,
  li.teilobj_name::character varying,
  li.biotopart::character varying,
  li.beschreibung::character varying,
  li.herkunft::character varying,
  li.kartierungsgrundlage::character varying,
  li.bedeutung::character varying,
  li.rechtsstatus::character varying,
  li.publikation::boolean,
  li.fotos::text,
  li.spezart::text,
  li.entscheid::character varying,
  li.intern_nutzung::character varying,
  li.intern_gefaehrdung::character varying,
  li.intern_empfehlung::character varying,
  li.intern_datum_erhebung::date,
  li.intern_bearbeiterimfeld::character varying,
  li.intern_kommentar::text,
  li.intern_letzte_mutation::date,
  li.intern_mutationsgrund::character varying,
  li.intern_spezart::text,
  li.gem_parz_liste::character varying,
  li.gem_bezeichnung_lage::character varying,
  li.gem_beschreibung_objekt::character varying,
  li.gem_ausfuehrliche_beschreibung_objekt::text,
  li.gem_bemerkungen_besonderheiten::text,
  li.gem_biodiversitaet_oekologie::character varying,
  li.gem_landschaftspraegung::character varying,
  li.gem_vernetzungsfunktion::character varying,
  li.gem_gesamtbeurteilung::character varying,
  li.gem_schutzziele::text,
  li.gem_empfehlung::text,
  li.gem_aenderung_vorhandenes_biotop::boolean,
  li.intern_letzte_aenderung::date,
  li.laenge_m::integer,
  li.last_modified::date,
  li.last_user::character varying,
  li.geometrie::geometry(MultiLineString,2056),
  li.oid_uuid::uuid,
  li.lebensraumnummer::character varying,
    -- additional utility columns
  a_bio_typ.bio_typ as bio_typ_derived
FROM {{ source('prod_gl_biotope', 'biotope_to_li') }} as li
LEFT JOIN {{ ref('assignment_table_bio_typ') }} as a_bio_typ
  ON a_bio_typ.lebensraumnummer = li.lebensraumnummer
