SELECT 
  gid::integer, -- NOT NULL
  kanton::character varying, 
  gemeinde::character varying(25), 
  objekt_nummer::character varying, 
  objekt_name::character varying, 
  teilobj_nr::character varying, 
  teilobj_name::character varying, 
  bedeutung::character varying, 
  biotopart::character varying, 
  beschreibung_de::character varying, 
  beschreibung_la::character varying, 
  artvorkommen::character varying, 
  artvorkommen_intern::character varying, 
  felderhebung::date, 
  bearbeitungimfeld::character varying, 
  kartierungsgrundlage::character varying, 
  kommentar::character varying, 
  publikation_biotopverzeichnis::boolean, 
  mutationsdatum::date, 
  mutationsgrund::character varying, 
  herkunft::character varying, 
  bund_nr::character varying, 
  bund_name::character varying, 
  bund_teilobj_nr::character varying, 
  bund_typ::character varying, 
  schutzqualitaet::character varying, 
  schutzart::character varying, 
  schutzdauer::integer, 
  status_biotopverzeichnis::character varying, 
  dokument_biotopverzeichnis::character varying, 
  foto_bezeichnung::character varying, 
  foto_datum::character varying, 
  foto_uri::character varying, 
  bemerkungen_2024::character varying, 
  objnr_2025::integer, 
  geometrie::geometry(MultiPoint,2056), 
  centr_e::integer, 
  centr_n::integer, 
  hm_nat_nr::character varying, 
  hm_nat_name::character varying, 
  fm_nat_nr::character varying, 
  fm_nat_name::character varying, 
  tww_nat_nr::character varying, 
  tww_nat_name::character varying, 
  tww_nat_a2_nr::character varying, 
  tww_nat_a2_name::character varying, 
  alg_nat_nr::character varying, 
  alg_nat_name::character varying, 
  aue_nat_nr::character varying, 
  aue_nat_name::character varying, 
  aue_nat_a2_nr::character varying, 
  aue_nat_a2_name::character varying, 
  ml_nat_nr::character varying, 
  ml_nat_name::character varying
FROM {{ source('prod_gl_biotope', 'biotope_to_pt') }}