SELECT 
  gid::bigint, -- NOT NULL
  kanton::character varying, 
  gemeinde::character varying, 
  objekt_nummer::character varying, 
  objekt_name::character varying, 
  teilobj_nr::character varying, 
  teilobj_name::character varying, 
  bedeutung::character varying, 
  biotopart::character varying, 
  beschreibung_de::character varying, 
  beschreibung_la::character varying, 
  artvorkommen::character varying, 
  artvorkommen_intern::character varying, 
  felderhebung::date, 
  bearbeitungimfeld::character varying, 
  kartierungsgrundlage::character varying, 
  bund_nr::character varying, 
  bund_name::character varying, 
  bund_teilobj_nr::character varying, 
  bund_typ::character varying, 
  kommentar::character varying, 
  schutzqualitaet::character varying, 
  schutzart::character varying, 
  schutzdauer::integer, 
  status_biotopverzeichnis::character varying, 
  dokument_biotopverzeichnis::character varying, 
  foto_bezeichnung::character varying, 
  foto_datum::character varying, 
  foto_uri::character varying, 
  publikation_biotopverzeichnis::boolean, 
  mutationsdatum::date, 
  mutationsgrund::character varying, 
  herkunft::character varying, 
  geometrie::geometry(MultiLineString,2056), 
  laenge_m::double precision, 
  centr_e::integer, 
  centr_n::integer, 
  bemerkungen_2024::character varying, 
  objnr_2025::integer, 
  ml_nat_nr::character varying, 
  ml_nat_lfm::double precision, 
  ml_nat_name::character varying
FROM {{ source('prod_gl_biotope', 'biotope_to_li') }}