WITH base as (
  SELECT 
    gid::integer, -- NOT NULL
    kanton::character varying, 
    objekt_nummer::character varying, 
    objekt_name::character varying, 
    teilobj_nr::character varying, 
    teilobj_name::character varying, 
    bedeutung::character varying, 
    biotopart::character varying, 
    lebensraumnummer::character varying, 
    beschreibung_de::character varying, 
    beschreibung_la::character varying, 
    artvorkommen::character varying, 
    artvorkommen_intern::character varying, 
    felderhebung::date, 
    bearbeitungimfeld::character varying, 
    kartierungsgrundlage::character varying, 
    kommentar::character varying, 
    typ_auenobjekt::character varying, 
    typ_amphibienlaichgebiet::character varying, 
    typ_hochmoortyp::character varying, 
    publikation_biotopverzeichnis::boolean, 
    mutationsdatum::date, 
    mutationsgrund::character varying, 
    herkunft::character varying, 
    geometrie::geometry(MultiPolygon,2056), 
    flaeche_m2::double precision, 
    centr_e::integer, 
    centr_n::integer, 
    schutzqualitaet::character varying, 
    schutzart::character varying, 
    schutzdauer::integer, 
    status_biotopverzeichnis::character varying, 
    dokument_biotopverzeichnis::character varying, 
    foto_bezeichnung::character varying, 
    foto_datum::character varying, 
    foto_uri::character varying, 
    bund_nr::character varying, 
    bund_name::character varying, 
    bund_teilobj_nr::character varying, 
    bund_typ::character varying, 
    hm_nat_nr::character varying, 
    hm_nat_ha::double precision, 
    hm_nat_name::character varying, 
    fm_nat_nr::character varying, 
    fm_nat_ha::double precision, 
    fm_nat_name::character varying, 
    tww_nat_nr::character varying, 
    tww_nat_ha::double precision, 
    tww_nat_name::character varying, 
    tww_nat_a2_nr::character varying, 
    tww_nat_a2_ha::double precision, 
    tww_nat_a2_name::character varying, 
    alg_nat_nr::character varying, 
    alg_nat_ha::double precision, 
    alg_nat_name::character varying, 
    aue_nat_nr::character varying, 
    aue_nat_ha::double precision, 
    aue_nat_name::character varying, 
    aue_nat_a2_nr::character varying, 
    aue_nat_a2_ha::double precision, 
    aue_nat_a2_name::character varying, 
    ml_nat_nr::character varying, 
    ml_nat_ha::double precision, 
    ml_nat_name::character varying, 
    objnr_2025::integer, 
    bemerkungen_2024::character varying, 
    oid_uuid::uuid
  FROM {{ source('prod_gl_biotope', 'biotope_to_sf') }}
),
added_cols as (
  SELECT
    base.*,
    (regexp_split_to_array(lebensraumnummer, '[,;]'))[1] as lebensraumnummer_first
  FROM base
)
SELECT 
  a.*,
  a_bio_typ.bio_typ as bio_typ_derived,
  a_bio_typ.bio_typ_beschreibung
FROM added_cols as a
LEFT JOIN {{ ref('assignment_table_bio_typ') }} as a_bio_typ
  ON a_bio_typ.lebensraumnummer = a.lebensraumnummer_first