WITH source AS (
SELECT 
  gid::bigint, -- NOT NULL
  geometrie::geometry(MultiPolygon,2056), 
  kanton::character varying, 
  objekt_nummer::character varying, 
  objekt_name::character varying, 
  teilobj_nr::character varying, 
  teilobj_name::character varying, 
  bedeutung::character varying, 
  biotopart::character varying, 
  beschreibung_de::character varying, 
  beschreibung_la::character varying, 
  artvorkommen::character varying, 
  artvorkommen_intern::character varying, 
  felderhebung::date, 
  bearbeitungimfeld::character varying, 
  kartierungsgrundlage::character varying, 
  bund_nr::character varying, 
  bund_name::character varying, 
  bund_teilojb_nr::character varying, 
  bund_typ::character varying, 
  typ_auenobjekt::character varying, 
  typ_amphibienlaichgebiet::character varying, 
  typ_hochmoortyp::character varying, 
  typ_pufferzone::character varying, 
  kommentar::character varying, 
  schutzqualitaet::character varying, 
  schutzart::character varying, 
  schutzdauer::integer, 
  status_biotopverzeichnis::character varying, 
  dokument_biotopverzeichnis::character varying, 
  foto_bezeichnung::character varying, 
  foto_datum::character varying, 
  foto_uri::character varying, 
  publikation_biotopverzeichnis::boolean, 
  mutationsdatum::date, 
  mutationsgrund::character varying, 
  herkunft::character varying, 
  gem_ns_zone::character varying, 
  kant_ns_gebiet::character varying, 
  nhg_vertrag::character varying, 
  gem_ns_zone_m2::integer, 
  kant_ns_gebiet_m2::integer, 
  nhg_vertrag_m2::integer, 
  flaeche_m2::double precision, 
  gid_2024::integer, 
  objektnr_2024::character varying, 
  objektname_2024::character varying, 
  teilobjnr_2024::character varying, 
  teilobjektname_2024::character varying, 
  bedeutung_2024::character varying, 
  bemerkungen_2024::character varying, 
  gid_1996::integer, 
  objektnr_1996::character varying, 
  teilobjnr_1996::character varying, 
  arten_1996::character varying, 
  bemerkungen_1996::character varying, 
  objnr_2025::integer, 
  teil_objnr_2025::integer, 
  centr_e::integer, 
  centr_n::integer, 
  hm_nat_nr::character varying, 
  hm_nat_ha::double precision, 
  hm_nat_name::character varying, 
  fm_nat_nr::character varying, 
  fm_nat_ha::double precision, 
  fm_nat_name::character varying, 
  tww_nat_nr::character varying, 
  tww_nat_ha::double precision, 
  tww_nat_name::character varying, 
  tww_nat_a2_nr::character varying, 
  tww_nat_a2_ha::double precision, 
  tww_nat_a2_name::character varying, 
  alg_nat_nr::character varying, 
  alg_nat_ha::double precision, 
  alg_nat_name::character varying, 
  aue_nat_nr::character varying, 
  aue_nat_ha::double precision, 
  aue_nat_name::character varying, 
  aue_nat_a2_nr::character varying, 
  aue_nat_a2_ha::double precision, 
  aue_nat_a2_name::character varying, 
  ml_nat_nr::character varying, 
  ml_nat_ha::double precision, 
  ml_nat_name::character varying, 
  flaeche_ha_gewichtet::double precision, 
  obj_flaeche_ha_gewichtet::double precision,
  oid_uuid::uuid
  FROM {{ source('prod_gl_biotope', 'biotope_to_sf_neu') }}
),
with_derived_columns AS (
SELECT 
  *,
  (length(split_part(beschreibung_de, ';Lebensraumnummer:', 2)) > 5)::boolean as non_unique_lebenraumnummer,
  (regexp_split_to_array(split_part(beschreibung_de, ';Lebensraumnummer:', 2), '[,;]'))[1] as first_lebensraumnummer
  -- TODO: Split this information apart in Database, rather than here for robustness sake!
  FROM source
)
SELECT 
  d.*,
  a_bio_typ.bio_typ as bafu_bio_typ

FROM with_derived_columns as d
LEFT JOIN {{ ref('assignment_table_bio_typ') }} as a_bio_typ
  ON a_bio_typ.lebensraumnummer = d.first_lebensraumnummer
