SELECT 
  sf.gid::integer,
  sf.kanton::character varying,
  sf.objekt_nummer::character varying,
  sf.objekt_name::character varying,
  sf.teilobj_nr::character varying,
  sf.teilobj_name::character varying,
  sf.biotopart::character varying,
  sf.beschreibung::character varying,
  sf.herkunft::character varying,
  sf.kartierungsgrundlage::character varying,
  sf.bedeutung::character varying,
  sf.rechtsstatus::character varying,
  sf.publikation::boolean,
  sf.fotos::text,
  sf.spezart::text,
  sf.entscheid::character varying,
  sf.intern_nutzung::character varying,
  sf.intern_gefaehrdung::character varying,
  sf.intern_empfehlung::character varying,
  sf.intern_datum_erhebung::date,
  sf.intern_bearbeiterimfeld::character varying,
  sf.intern_kommentar::text,
  sf.intern_letzte_mutation::date,
  sf.intern_mutationsgrund::character varying,
  sf.intern_spezart::text,
  sf.gem_parz_liste::character varying,
  sf.gem_bezeichnung_lage::character varying,
  sf.gem_beschreibung_objekt::character varying,
  sf.gem_ausfuehrliche_beschreibung_objekt::text,
  sf.gem_bemerkungen_besonderheiten::text,
  sf.gem_biodiversitaet_oekologie::character varying,
  sf.gem_landschaftspraegung::character varying,
  sf.gem_vernetzungsfunktion::character varying,
  sf.gem_gesamtbeurteilung::character varying,
  sf.gem_schutzziele::text,
  sf.gem_empfehlung::text,
  sf.gem_aenderung_vorhandenes_biotop::boolean,
  sf.intern_letzte_aenderung::date,
  sf.flaeche_m2::integer,
  sf.last_modified::date,
  sf.last_user::character varying,
  sf.geometrie::geometry(MultiPolygon,2056),
  sf.oid_uuid::uuid,
  sf.id_old::integer,
  sf.lebensraumnummer::character varying,

  -- additional utility columns
  a_bio_typ.bio_typ as bafu_bio_typ
FROM {{ source('prod_gl_biotope', 'biotope_to_sf') }} as sf 
LEFT JOIN {{ ref('assignment_table_bio_typ') }} as a_bio_typ
  ON a_bio_typ.lebensraumnummer = sf.lebensraumnummer
