services:
  dbt-dev: 
    image: dbt_image:latest
    container_name: dbt-container
    network_mode: host  
    environment:
      - DISPLAY=host.docker.internal:0.0 # set display environment to local host IP
    volumes:
      - ..:/project
      - ~/.ssh:/home/user/.ssh # forward ssh keys (linux-specific)     
    tty: true

  postgis-srv:
    image: postgis:dev
    container_name: postgis-container
    network_mode: host
    # start using this when starting next project
    # volumes:
    #   - ./postgis_var/:var/lib/postgresql/data/
 