services:
  dbt-dev: 
    image: dbt_image:latest
    container_name: dbt-container
    network_mode: devnet  
    environment:
      - DISPLAY=host.docker.internal:0.0 # set display environment to local host IP
    volumes:
      - ..:/project
      - ~/.ssh:/home/user/.ssh # forward ssh keys (linux-specific)     
    tty: true

  postgis-srv:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgis-container
    attach: false
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    network_mode: devnet
    ports:
      - 5432:5432 # change to "127.0.0.1:5432:5432"
 
