services:
  dbt-dev: 
    image: dbt_image:latest
    container_name: dbt-container
    network_mode: devnet  
    
    volumes:
      - ..:/project
      - ~/.ssh:/home/user/.ssh # forward ssh keys (linux-specific)  
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/developer/.Xauthority   
    
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/developer/.Xauthority
      - MPLBACKEND=TkAgg
      
    tty: true

  postgis-srv:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgis-container
    attach: false
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    network_mode: devnet
    ports:
      - 5432:5432 # change to "127.0.0.1:5432:5432"
 
