sources:
  - name: src_prod_gl_arten
    database: "{{ target.database }}"
    schema: prod_gl_arten
    tables:
      - name: artvorkommen_gl_pt
      - name: cat_art
  
  - name: src_dbt_arten
    database: "{{ target.database }}"
    schema: dbt_arten
    tables:
      - name: imp_wisgl_besonderearten

