
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_biotope'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_biotope_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


on-run-start:
  - '{{ ili_utils.reset_ili_sequence("dbt_biotope", 101) }}'


vars:
  data_dataset:
    datasetname: data

  data_basket:
    t_id: 100
    topic: placeholder_topic
    dataset_tid: 1

  data_t_id_offset: 101

models:
  dbt_biotope:
    +grants:
      select: ['prod_gl_biotope_read']  

seeds:
  dbt_biotope:
     +delimiter: ";" # default project delimiter for seeds will be "|"