dbt_biotope:
  target: dev
  outputs:
    dev:
      dbname: test-db
      host: localhost
      pass: "{{ env_var('DB_PASSWORD') }}" # export DB_PASSWORD='...' in bashrc
      port: 5432
      schema: dbt_biotope
      threads: 1
      type: postgres
      user: postgres
      
    windmill-iap:
      # use this profile when running dbt project from windmill runner
      host: srv-gisiap-02.glnet.ch
      dbname: glarus
      pass: "{{ env_var('DB_PASSWORD') }}" # export DB_PASSWORD='...' in bashrc
      port: 5432
      schema: dbt_quellkataster
      threads: 1
      type: postgres
      user: gisuploadmanager