sources:
  - name: prod_gl_ersatzbiotope
    database: "{{ target.database }}"
    schema: prod_gl_ersatzbiotope
    tables:
      - name: ersatzbiotope_sf
      - name: ersatzbiotope_li
      - name: ersatzbiotope_pt
      - name: cat_kategorie_ersatzmassnahme

  - name: gl_ersatzbiotope
    database: "{{ target.database }}"
    schema: gl_ersatzbiotope
    tables:
      - name: ersatzmassnahme_catalogue