
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_dbu_aue_quellkataster'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbu_aue_quellkataster_profile'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start: 
  - '{{ run_start_parsing() }}' # function defined in macros/ili_utils.sql

vars:
  target_ili_schema: dbu_aue_quellkataster

  datasets:
    dataset_access:
      t_id: 1
      dataset: access-datenquelle
    dataset_alpquellen:
      t_id: 2
      dataset: alpquellen-datenquelle
    dataset_new:
      t_id: 3
      dataset: neuerfassung

  # Basket variables
  # These get inserted into the target schema's t_ili2db_basket table
  # when the macro 'write_basket()' is run.    
  baskets:
    basket_quellkataster_access:
      t_id: 1
      topic: Grundwasseraustritte_intern
      dataset_t_id: NULL 
    basket_quellkataster_alpquellen:
      t_id: 2
      topic: Grundwasseraustritte_intern
      dataset_t_id: NULL

  # Classnames variables
  # Usage example:
  # '{{ var('classnames')['Quelle_intern'] }}'::character varying as t_type,
  classnames:
    Quelle_intern: Prod_Quellkataster_V1.Quelle.Quelle_intern
  

models:
  dbt_dbu_aue_quellkataster:
    +grants:
      select: ['dbu_aue_quellkataster_read']
    +post-hook: 
    - 'ALTER {{model.config.materialized}} {{this}} OWNER TO "dbu_aue_quellkataster_write"'

