SELECT 
  t_id,
  t_basket,
  t_ili_tid,
  aname::character varying,
  grundwasserleiter_typ::character varying,
  quelltyp::character varying,
  fassungsart::character varying,
  nutzungszustand::character varying,
  trinkwasser::character varying,
  zweck::character varying,
  oeffentliches_interesse::character varying,
  schuettung_minimal::numeric(9,2),
  schuettung_mittel::numeric(9,2),
  schuettung_maximal::numeric(9,2),
  NULL::character varying as zustroembereich_erforderlich,
  geometrie,
  hoehe::numeric,
  notwasserversorgung::varchar,
  NULL::character varying as name_wv,
  NULL::character varying as ordnungs_nr,
  NULL::character varying as ortschaft,
  NULL::character varying as postleitzahl,
  NULL::character varying as parz_nr,
  NULL::character varying as lagegenauigkeit,
  NULL::integer as schachtueberstand,
  NULL::character varying as fassungsart_beschreibung,
  NULL::character varying as fassungsabdeckung,
  NULL::character varying as fassungszustand,
  NULL::character varying as schachttyp,
  NULL::integer as anzahl_zuleitungen,
  NULL::boolean as schloss,
  NULL::character varying as fassungseigentuemer,
  NULL::character varying as verwendungsart,
  NULL::character varying as verwendungszweck_beschreibung,
  NULL::boolean as wva_nutzung,
  NULL::boolean as wva_nutzung_ergaenzen,
  NULL::boolean as wva_nutzung_streichen,
  NULL::boolean as wva_nutzung_lage_neu,
  NULL::character varying as datenherkunft,
  NULL::character varying as aufgenommen_durch,
  NULL::date as erhebungsdatum,
  NULL::date as feldbegehung,
  NULL::date as objektbereinigung,
  NULL::varchar as schutzzone,
  NULL::character varying as kontaktperson,
  NULL::character varying as bemerkungen
FROM {{ ref('intermediate_alpquellen_disjoint') }}

