{{ config(materialized='table')}} -- so type casts are actually done and checked

SELECT 
  t_id,
  t_basket,
  t_ili_tid,
  identifikator::varchar,
  aname::varchar,
  grundwasserleiter_typ::varchar,
  quelltyp::varchar,
  fassungsart::varchar,
  nutzungszustand::varchar,
  trinkwasser::varchar,
  zweck::varchar,
  oeffentliches_interesse::varchar,
  schuettung_minimal::numeric(9,2),
  schuettung_mittel::numeric(9,2),
  schuettung_maximal::numeric(9,2),
  NULL::varchar as zustroembereich_erforderlich,
  geometrie,
  hoehe::numeric,
  notwasserversorgung::varchar,
  name_wv::varchar,
  ordnungs_nr::varchar,
  ortschaft::varchar,
  postleitzahl::varchar,
  parz_nr::varchar,
  lagegenauigkeit::varchar,
  schachtueberstand::integer,
  fassungsart_beschreibung::varchar,
  fassungsabdeckung::varchar,
  fassungszustand::varchar,
  schachttyp::varchar,
  anzahl_zuleitungen::integer,
  schloss::boolean,
  fassungseigentuemer::varchar,
  verwendungsart::varchar,
  verwendungszweck_beschreibung::varchar,
  wva_nutzung::boolean,
  wva_nutzung_ergaenzen::boolean,
  wva_nutzung_streichen::boolean,
  wva_nutzung_lage_neu::boolean,
  datenherkunft::varchar,
  aufgenommen_durch::varchar,
  erhebungsdatum::date,
  feldbegehung::date,
  objektbereinigung::date,
  schutzzone::varchar,
  kontaktperson::varchar,
  bemerkungen::varchar
FROM {{ ref('b_quelle_union') }}

