SELECT   
  id,
	1 as t_basket,
	id_art,
	name_deutsch as ,
	name_lateinisch,
	organismengruppe,
	schutz_status_schweiz,
	schutz_status_kt_gl,
	rote_liste_status,
	radius,
	genau,
	substrat,
	foerderungsmassnahmen,
	finder,
	funddatum,
	hinzugefuegt_am,
	kantonsintern,
	verwaltungsintern,
	astatus as status,
	bemerkungen,
	fotos, 
	geometrie
FROM {{ ref('intr_wisgl_export_dedup') }}