name: 'dbt_ersatzbiotope'
version: '1.0.0'

profile: 'dbt_ersatzbiotope_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  export_config:
    catalogue_basket_t_id: 2 # used in run-operation macro 'write_kategorie_catalogue()'
    starting_data_tid: 100
    gl_ersatzbiotope_data_basket_tid: 36
    pub_gl_ersatzbiotope_data_basket_tid: 6

on-run-start:
  - ALTER SEQUENCE dbt_ersatzbiotope.t_ili2db_seq RESTART WITH {{ var('export_config')['starting_data_tid'] }}

models:
  dbt_ersatzbiotope:
    +grants:
      select: ['prod_gl_biotope_read']
    +post-hook: 
    - 'ALTER {{model.config.materialized}} {{this}} OWNER TO "prod_gl_biotope_write"'

