name: 'dbt_ersatzbiotope'
version: '1.0.0'

profile: 'dbt_ersatzbiotope_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  starting_data_tid: 100 # value t_ili2db_seq is set to (both during data creation on dbt schema as well as on target before transferring) 
  
  export_config_pub:   
    data_basket_tid: 3

  export_config_gl:
    starting_data_tid: 100 
    data_basket_tid: 36
    
  macro_variables:
    catalogue_basket_t_id: 2 # used in run-operation macro 'write_kategorie_catalogue()'


on-run-start:
  - ALTER SEQUENCE dbt_ersatzbiotope.t_ili2db_seq RESTART WITH {{ var('starting_data_tid') }}

models:
  dbt_ersatzbiotope:
    +grants:
      select: ['prod_gl_biotope_read']
    +post-hook: 
    - 'ALTER {{model.config.materialized}} {{this}} OWNER TO "prod_gl_biotope_write"'

