sources:
  - name: raw_sources
    database: test-db
    schema: src
    tables:
      - name: alpquellen
      - name: access_objektdaten

  - name: target
    database: test-db
    schema: dbu_aue_quellkataster
    tables:
    - name: quelle


