sources:
  - name: raw_sources
    database: "{{ target.database }}"
    schema: dbt_quellkataster
    tables:
      - name: src_alpquellen
      - name: src_access_objektdaten
      - name: src_access_messdaten
      - name: src_nachtraege 

