select
  {{ adapter.quote("fid") }}::integer as pkey_src,
  --{{ adapter.quote("schluessel") }}, -- incomplete data
  {{ adapter.quote("objektname") }} as aname,
  {{ adapter.quote("lokalbezeichnung") }},
  {{ adapter.quote("gemeinde") }} as ortschaft,
  NULLIF({{ adapter.quote("postleitzahl") }}, '')::integer as postleitzahl,
  {{ adapter.quote("x-koordinate") }}::integer as x_koordinate,
  {{ adapter.quote("y-koordinate") }}::integer as y_koordinate,
  NULLIF({{ adapter.quote("parz_nr") }}, '')::integer as parz_nr,
  {{ adapter.quote("fassungseigentuemer") }},
  {{ adapter.quote("ok_terrain") }}::double precision as hoehe,
  NULL::integer as schachtueberstand,
  {{ adapter.quote("ordnungs-nr") }}::varchar as ordnungs_nr,
  {{ adapter.quote("lagegenauigkeit") }},
  {{ adapter.quote("verwendungszweck") }},
  {{ adapter.quote("verwendungsart") }},
  {{ adapter.quote("fassungsart") }},
  {{ adapter.quote("fassungszustand") }},
  {{ adapter.quote("fassungsabdeckung") }},
  {{ adapter.quote("schachttyp") }},
  {{ adapter.quote("datenherkunft") }},
  {{ adapter.quote("kontaktperson") }},
  {{ adapter.quote("bemerkungen objektdaten") }} as bemerkungen,
  {{ adapter.quote("foto") }},
  {{ adapter.quote("foto-negativ-nr_1") }} as foto_negativ_nr_1,
  {{ adapter.quote("foto-negativ-nr_2") }} as foto_negativ_nr_2,
  {{ adapter.quote("foto-negativ-nr_3") }} as foto_negativ_nr_3,
  {{ adapter.quote("fassung") }},
  {{ adapter.quote("schutzzone") }} as schutzzone,
  NULLIF({{ adapter.quote("anzahl_zuleitungen") }}, '')::integer as anzahl_zuleitungen,
  {{ adapter.quote("schloss") }},
  {{ adapter.quote("aufgenommen_durch") }},
  NULL::date as erhebungsdatum, -- 3 entries in a PITA format -> enter manually
  {{ adapter.quote("alte_ordnungs-nr") }} as alte_ordnungs_nr,
  to_date(NULLIF({{ adapter.quote("feldbegehung") }},''), 'DD.MM.YYYY') as feldbegehung,
  to_date(NULLIF({{ adapter.quote("objektbereinigung") }},''), 'DD.MM.YYYY') as objektbereinigung,
  {{ adapter.quote("wva-nutzung") }} as wva_nutzung,
  {{ adapter.quote("wva-nutzung_ergaenzen") }} as wva_nutzung_ergaenzen,
  {{ adapter.quote("wva-nutzung_streichen") }} as wva_nutzung_streichen,
  {{ adapter.quote("wva-nutzung_lage_neu") }} as wva_nutzung_lage_neu,
  ST_SetSRID(ST_Point("x-koordinate"::integer, "y-koordinate"::integer), 2056) as geometrie
from {{ source('raw_sources', 'src_nachtraege') }}
