-- 'TODO' -> von Fachleuten zu befüllen

SELECT
  pkey_src,
  nextval('dbu_aue_quellkataster.t_ili2db_seq'::regclass) as t_id,
  {{ var('baskets')['basket_quellkataster_access']['t_id'] }}::bigint as t_basket,
  uuid_generate_v4() as t_ili_tid, 
  aname,
  'unbestimmt' as grundwasserleiter_typ,
  NULL as quelltyp,
  'TODO' as fassungsart,
  'TODO' as nutzungszustand,
  'TODO' as trinkwasser,
  NULL as zweck,
  NULL as oeffentliches_interesse,
  m.schuettung_minimal,
  m.schuettung_mittel,
  m.schuettung_maximal,
  NULL as zustroembereich_erforderlich,
  geometrie,
  hoehe,
  NULL as notwasserversorgung,
  NULL as name_wv,
  ordnungs_nr,
  ortschaft,
  postleitzahl,
  parz_nr,
  lagegenauigkeit,
  schachtueberstand,
  fassungsart as fassungsart_beschreibung,
  fassungsabdeckung,
  fassungszustand,
  schachttyp,
  anzahl_zuleitungen,
  schloss,
  fassungseigentuemer,
  verwendungsart,
  verwendungszweck as verwendungszweck_beschreibung,
  wva_nutzung,
  wva_nutzung_ergaenzen,
  wva_nutzung_streichen,
  wva_nutzung_lage_neu,
  datenherkunft,
  aufgenommen_durch,
  erhebungsdatum,
  feldbegehung,
  objektbereinigung,
  schutzzone_erforderlich,
  kontaktperson,
  bemerkungen
FROM {{ ref('staging_access_objektdaten') }} as o
LEFT JOIN {{ ref('agg_messungen') }} as m
  ON o.pkey_src = m.fkey_quelle_src