-- 'TODO' -> von Fachleuten zu befüllen

SELECT
  aname::varchar,
  'unbestimmt'::varchar,
  NULL::varchar as quelltyp,
  'TODO'::varchar as fassungsart,
  'TODO'::varchar as nutzungszustand,
  'TODO'::varchar as trinkwasser,
  zweck::varchar,
  oeffentliches_interesse::varchar,
  COALESCE(schuettung_minimal, {{null_substitute}})::numeric as schuettung_minimal,
  COALESCE(schuettung_mittel, {{null_substitute}})::numeric as schuettung_mittel,
  COALESCE(schuettung_maximal, {{null_substitute}})::numeric as schuettung_maximal,
  NULL::varchar as zustroembereich_erforderlich,
  geometrie,
  hoehe::numeric,
  notwasserversorgung::varchar,
  NULL::varchar as name_wv,
  NULL::varchar as ordnungs_nr,
  NULL::varchar as ortschaft,
  NULL::varchar as postleitzahl,
  NULL::varchar as parznr,
  NULL::varchar as lagegenauigkeit,
  NULL::integer as schachtueberstand,
  NULL::varchar as fassungsart_beschreibung,
  NULL::varchar as fassungsabdeckung,
  NULL::varchar as fassungszustand,
  NULL::varchar as schachttyp,
  NULL::integer as anzahl_zuleitungen,
  NULL::boolean as schloss,
  NULL::varchar as fassungseigentuemer,
  NULL::varchar as verwendungsart,
  NULL::varchar as verwendungszweck_beschreibung,
  NULL::boolean as wva_nutzung,
  NULL::boolean as wva_nutzung_ergaenzen,
  NULL::boolean as wva_nutzung_streichen,
  NULL::boolean as wva_nutzung_lage_neu,
  NULL::varchar as datenherkunft,
  NULL::varchar as aufgenommen_durch,
  NULL::date as erhebungsdatum,
  NULL::date as feldbegehung,
  NULL::date as objektbereinigung,
  NULL::boolean as schutzzone_erforderlich,
  NULL::varchar as kontaktperson,
  NULL::varchar as bemerkungen
FROM {{ ref('staging_access_objektdaten') }}