
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_arten'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_arten'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_arten:
    +grants:
      select: ['prod_gl_arten_read']
  
  # tags mirroring models dir structure
    audits:
      wisgl_export:
        +tags: audit_wisgl_export
      wisgl_import:
        +tags: audit_wisgl_import
      update_artvorkommen_id_art:
        +tags: audit_update_artvorkommen_id_art

    transformations:
      wisgl_export:
        +tags: wisgl_export
      wisgl_import:
        +tags: wisgl_import
      update_artvorkommen_id_art:
        +tags: update_artvorkommen_id_art



vars:
  # ili setup
  datasets:
    default_dataset:
      t_id: 2
      datasetname: besonderewaldarten

  baskets:
    default_basket:
      t_id: 1
      topic: GL_BesondereWaldarten_V1.GL_BesondereWaldarten
      dataset_t_id: 2
