dbt_arten:
  target: dev
  outputs:
    dev:
      dbname: test-db
      host: postgis-container
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      schema: dbt_arten
      threads: 1
      type: postgres
      user: postgres
  
    windmill-iap:
      # use this profile when running dbt project from windmill runner
      host: srv-gisiap-02.glnet.ch
      dbname: glarus
      pass: "{{ env_var('DB_PASSWORD') }}" # export DB_PASSWORD='...' in bashrc
      port: 5432
      schema: dbt_arten
      threads: 1
      type: postgres
      user: gisuploadmanager
  